### ISSUE TITLE
Centralized remote GitHub CI config

### ISSUE THREAD

**Issue by bocharsky-bw** [SymfonyCasts/.github#1]
See https://github.com/orgs/SymfonyCasts/projects/7/views/1?sortedBy%5Bdirection%5D=asc&sortedBy%5BcolumnId%5D=33394902&pane=issue&itemId=21066810

Hooked up repos:
- https://github.com/SymfonyCasts/reset-password-bundle/pull/261
- https://github.com/SymfonyCasts/verify-email-bundle/pull/139
- https://github.com/knpuniversity/oauth2-client-bundle/pull/398
- https://github.com/SymfonyCasts/messenger-monitor-bundle/pull/48

**Comment by weaverryan** [comment]
🥳
